name: Main branch changes workflow

concurrency: main

on:
  push:
    branches: [ "main" ]

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RG-Systems/vite-project-cdk/.github/workflows/deploy.yml@main
        with:
          commit: ${{ github.sha }}
          environment: "qa"

  build:
    needs: infra
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn build

  deploy:
    needs:
      - build
      - infra

    environment:
      name: qa
      url: ${{ needs.infra.outputs.url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::503479554940:role/RG-Systems-GH-Actions
          role-session-name: vp-cdk-deploy
          aws-region: us-east-1
      - run: |
          aws s3 sync ./dist s3://${{ needs.infra.outputs.bucket }}/${{ github.sha }}
          aws cloudfront create-invalidation --distribution-id ${{ needs.infra.outputs.id }} --paths "/*"

